on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
    tags:
      - 'v*'
jobs:
  docker:
    name: Build docker image and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: pikokr/mc-router-manager
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
