on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
    tags:
      - 'v*'
jobs:
  docker:
    name: Build docker image and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Metadata
        uses: docker/metadata-action@v5
      - name: Login to docker hub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
